### ISSUE TITLE
Javascript Error in Windows 10/7 with release 0.3.3 and 0.3.5

### ISSUE THREAD

**Issue by msvabik** [Enrico204/Whatsapp-Desktop#1]
Hello
An error window will appear when the message is received:
![2017-06-27 10_45_21-issues enrico204_whatsapp-desktop - firefox developer edition](https://user-images.githubusercontent.com/29727076/27578925-f8335826-5b25-11e7-8ca4-ba248877a4a9.png)

**Comment by Enrico204** [comment]
Hi @msvabik , I'll fix it as soon as possible! :-)

**Comment by Enrico204** [comment]
Hi @msvabik , I've fixed this bug in v0.3.6, you can find it in "Releases" :-)

**Comment by msvabik** [comment]
Hi Enriko, thank you very much for a quick fix.

**Comment by ceyhunnabiyev** [comment]
Hi @Enrico204 , 
Please create your own Archlinux  package for whatisapp-desktop. There is no any update in Archlinux(AUR) since you took over the project.

**Comment by Enrico204** [comment]
Hi @ceyhunnabiyev , you should open a new issue for that. BTW I sent a message to "whatsapp-desktop" package maintainer @bil-elmoussaoui which was packaging for AUR on the old repository.
