### ISSUE TITLE
Setting an option makes the app blank

### ISSUE THREAD

**Issue by sovetskikh** [Enrico204/Whatsapp-Desktop#102]
### System details

* OS: Arch Linux, Kernel ver: 4.15.5-1-ARCH, UTF8 es-ES.
* App Version: 0.4.2-2 (installed from AUR)
* If Linux, Desktop Environment: KDE Plasma 5.12.2-1, Kwin 5.12.2-1

### Expected behavior

I was trying to change some settings.

### Actual behavior

When saved, the app will turn blank and won't work until I remove ~/.config/whatsapp-desktop/settings.json 

### Step to reproduce the behavior

Set an option and save.

Screenshot:
![screenshot_20180227_122636](https://user-images.githubusercontent.com/20043656/36726298-8365a15c-1bb9-11e8-8878-b29c6ecab1ac.png)

**Comment by Enrico204** [comment]
Hi @sovetskikh , can you please check if this bug still in latest version (0.5.0) ? Thanks :-)

**Comment by sovetskikh** [comment]
It's not completely solved but at least it's fairly usable and i don't have to delete anything. Now I only have to restart the app, which is a big improvement.

Here's a video: 
https://youtu.be/HHd9cWcWCRg

And here's the log file: 
[log.log](https://github.com/Enrico204/Whatsapp-Desktop/files/1866372/log.log)

**Comment by Enrico204** [comment]
Ok thanks for testing, I'll setup your environment (Arch, KDE, ...) in order to reproduce this issue :-)

**Comment by sovetskikh** [comment]
Thanks to you!

**Comment by Enrico204** [comment]
@sovetskikh Can you please indicate which options trigger this behavior? I have a VM with the same environment as yours, still I can't reproduce this issue :-(

**Comment by Enrico204** [comment]
I'm closing this issue as I can't reproduce this behavior. Please, reopen it if you still have this problem :-)
