### ISSUE TITLE
Gnome cursor freezes in pointer state when downloading an image.

### ISSUE THREAD

**Issue by Ansis100** [Enrico204/Whatsapp-Desktop#106]
### System details

* OS: Ubuntu Gnome 16.04
* App Version: 0.4.2
* If Linux, Desktop Environment: Gnome 3

### Expected behavior

Download button on image toolbar opens directory selection and the user selects where to download the image.
(Suggestion) Download button on image toolbar downloads it to a previously specified directory. 

### Actual behavior

The directory selection opens and the cursor gets stuck in a pointer position. Unable to interact with other apps using the cursor, can only issue commands by opening the terminal using a keyboard shortcut. Usually doesn't happen after a `shutdown -r now`

### Step to reproduce the behavior

Not sure if it's only for me, but Actual behaviour basically describes it.

**Comment by Enrico204** [comment]
Definitively related to #61, we'll track updates on that issue
