### ISSUE TITLE
Flathub support

### ISSUE THREAD

**Issue by charlesjt** [Enrico204/Whatsapp-Desktop#111]
Currently a flatpak package is already available, so it would be great to be able to find the application on flathub (https://beta.flathub.org/home), which is integrated into the distros stores that support it natively.

**Comment by Enrico204** [comment]
The reason that this app is not in flathub (yet) is explained in #79 . I'll update that issue when I'll be able to fix freedesktop version and be able to upload the flatpak over flathub :-)
