### ISSUE TITLE
[Feature Request] Facebook Messenger tab

### ISSUE THREAD

**Issue by Sadi58** [Enrico204/Whatsapp-Desktop#115]
Thanks a lot for this great utility.
I wonder if this could be enhanced without too much effort to have a tabbed window containing WhatsApp Messenger as well as Facebook Messenger, perhaps by combining two projects into one (see https://github.com/sindresorhus/caprine), which could also mean more efficient use of computer resources...

**Comment by Enrico204** [comment]
Right now, this is not the scope of this project. Also, there are a number of multi-protocol clients around, even based on Electron like this. Sorry, this will not happen in the near future.
