### ISSUE TITLE
Load custom chat background broken on v0.5.0

### ISSUE THREAD

**Issue by sat3ll** [Enrico204/Whatsapp-Desktop#117]
### System details

* OS: Fedora 27 Linux, x86_64
* App Version: v0.5.0
* Desktop Environment: KDE Plasma 5
* GPU Rendering Disabled in Whatsapp-Desktop settings.

### Expected behavior

After update to v0.5.0, wallpaper did not load. Choosing another image should force it to load again.

### Actual behavior

After the update to v0.5.0, wallpaper stopped being loaded, even trying to reapply.

### Step to reproduce the behavior

Apply/Reapply custom chat background.

**Comment by Enrico204** [comment]
Actually, this bug is present on all versions because of some changes into the webapp code from Whatsapp :-)

**Comment by Enrico204** [comment]
Fixed :-)
