### ISSUE TITLE
API for send message and receive message

### ISSUE THREAD

**Issue by realreef** [Enrico204/Whatsapp-Desktop#120]
### System details

* OS: Centos 7.5
* App Version: lates
* If Linux, Desktop Environment: 

### Expected behavior

can provide API to send messages and receive messages

**Comment by Enrico204** [comment]
Sorry, but the goal of this project is to provide an usable desktop version of Whatsapp Web app to human, not to bot. You can always look on GitHub for projects who already provide these APIs
