### ISSUE TITLE
Error trying to run int on windows 10

### ISSUE THREAD

**Issue by alemdg** [Enrico204/Whatsapp-Desktop#121]
### System details

* OS: Windows 10, EN
* App Version: latest from github

### Actual behavior

executing  yarn install from console with Admin priv..

error electron-installer-flatpak@0.8.0: The platform "win32" is incompatible with this module.

**Comment by Enrico204** [comment]
Hi @alemdg , developing this project on Windows is not supported, only released version are. You can download the latest release here: https://github.com/Enrico204/Whatsapp-Desktop/releases/latest

**Comment by alemdg** [comment]
thanks
