### ISSUE TITLE
Whatsapp-Desktop should use correct (or correct-ish) user agent string

### ISSUE THREAD

**Issue by eliezerlp** [Enrico204/Whatsapp-Desktop#15]
I was very alarmed the other day when I showed usage from an OS X based machine. I could not remember the last time I was using OS X and signed into WhatsApp.

A couple of days later It hits me that it was this app's useragent.

This is another Electron based project that solved this: https://github.com/jiahaog/nativefier/issues/166

I am not sure it needs to be super in depth like trying to march the Chrome version as they did but at least match the OS version.

I did see that process.platform is used for only running certain functions on certain OSes. Maybe it can somehow be reused (I don't know js at all)...

**Comment by Enrico204** [comment]
Thanks @eliezerlp , actually that behaviour was caused by the hardcoded user-agent. It's fixed in last commit :-)

**Comment by eliezerlp** [comment]
I just built from Master and can confirm it looks good now. Matches my OS (Linux x86_64) in the "Logged in computers" via the WhatsApp Web page in the mobile app.
