### ISSUE TITLE
Add a .desktop file in order to be listed as app in gnome

### ISSUE THREAD

**Issue by rodrigoaguilera** [Enrico204/Whatsapp-Desktop#17]
I'm used to the telegram app in debian with gnome and soon I installed is it listed in the app list.

I just installed this app using the deb package from the releases page and I just have the "Whatsapp" command available to launch the app.

I am not a desktop app developer but I believe is because app ship with a .desktop file in the correct location.
Telegram for example
https://github.com/telegramdesktop/tdesktop/tree/dev/lib/xdg
But in the .deb file is in a different location
https://packages.debian.org/buster/amd64/telegram-desktop/filelist

PS: now that I see the file that defines the protocol. Does whatsapp have a protocol for opening links? Does this app handle it?

**Comment by Enrico204** [comment]
I don't know if WhatsApp has a link protocol, I'll check for that. In the meantime, I'll add a .desktop file.

**Comment by rodrigoaguilera** [comment]
I noticed that the app itself can create a .desktop file when you check the option "auto start at login" in $HOME/.config/autostart 
```
[Desktop Entry]
Type=Application
Version=1.0
Name=WhatsApp
Comment=WhatsAppstartup script
Exec=/opt/whatsapp-desktop/WhatsApp
StartupNotify=false
Terminal=false
```
It should be similar to that one I guess

**Comment by Enrico204** [comment]
Yes, that file is created by a Node/Electron library :-)

**Comment by Enrico204** [comment]
Desktop file entry added :-)

**Comment by rodrigoaguilera** [comment]
Thanks!
