### ISSUE TITLE
RPM Installation fails on Fedora 26

### ISSUE THREAD

**Issue by mhoeher** [Enrico204/Whatsapp-Desktop#19]
I tried to install the RPM - I am using Fedora 26. Here are the relevant logs:

```bash
sudo yum install ./WhatsApp-0.3.12-1.x86_64.rpm 
Error: 
 Problem: conflicting requests
  - nothing provides libffmpeg.so()(64bit) needed by WhatsApp-0.3.12-1.x86_64
```

I am now running the version provided as zipped tar, which works great by the way ;-)

The tar contained the mentioned `libffmpeg.so`; I guess it is also part of the RPM package? Maybe something's wrong with the RPMs req/prov settings?

**Comment by Enrico204** [comment]
Actually this issue is fixed, but the current RPM was not rebuild after it. I'll make a new RPM soon :-)

**Comment by mhoeher** [comment]
Cool, thank you!
