### ISSUE TITLE
Archlinux package for whatsapp-desktop

### ISSUE THREAD

**Issue by ceyhunnabiyev** [Enrico204/Whatsapp-Desktop#2]
There is no any update in Archlinux(AUR) since you took over the development of the project.

**Comment by Enrico204** [comment]
Hi @ceyhunnabiyev , I wrote to @bil-elmoussaoui which created the AUR package in the first place. I hope that he can continue to update AUR with newer versions of this project :-)
I'll update this issue

**Comment by bil-elmoussaoui** [comment]
I've updated the AUR package to the latest version 0.3.6

**Comment by Enrico204** [comment]
Thanks @bil-elmoussaoui :-)

**Comment by ceyhunnabiyev** [comment]
Hi @bil-elmoussaoui  ,
Please update the AUR package to version 0.3.7.

**Comment by bil-elmoussaoui** [comment]
Alright i will take care of that
