### ISSUE TITLE
error while loading shared libraries: libXss.so.1

### ISSUE THREAD

**Issue by jwich71** [Enrico204/Whatsapp-Desktop#20]
When I start Whatsapp from Whatsapp-Desktop-0.3.11/dist/WhatsApp-linux-x64/WhatsApp under Fedora 26, I get this error:
error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

**Comment by Enrico204** [comment]
You need to install libXScrnSaver :-)
`yum install libXScrnSaver`
