### ISSUE TITLE
Tray icon should indicate if there are unread messages

### ISSUE THREAD

**Issue by Termuellinator** [Enrico204/Whatsapp-Desktop#21]
so far, i'm pretty pleased with this client, but one thing bothers me: when it's minimized to tray, i have no indication if there are messages waiting.
If i understand the repo correctly, you already have a different icon for when there is a warning so i would assume this shouldn't be too hard? ^^

If i was to decide, i would rather have the current green icon be the notification and a more pale one (maybe just the white outlines?) for when there are no messages.

**Comment by Termuellinator** [comment]
in case it helps, i've put together my proposal for the "no message"-icons:


no messages:
![icon-no-messages 2x](https://user-images.githubusercontent.com/22668785/29703658-c1e76940-8976-11e7-8a36-94a1c01b3b38.png)
no messages + warning:
![icon-no-messages-warning 2x](https://user-images.githubusercontent.com/22668785/29703661-c500ec14-8976-11e7-9463-35d183039cd8.png)

**Comment by Enrico204** [comment]
A full white icon might be an issue on white backgrounds. Maybe we can add a "red dot" (just like the "badge" feature).

**Comment by Termuellinator** [comment]
Due to the shadow, the icon would still be kind of visible on white background.
But the idea of a red dot is also nice, wire indicades messages the same way.
Something like that maybe:
![icon-new-messages 2x](https://user-images.githubusercontent.com/22668785/29714435-832b667a-89a3-11e7-9ffa-62b4a64061a7.png)
![icon-new-messages-warning 2x](https://user-images.githubusercontent.com/22668785/29714442-8a8b1cc6-89a3-11e7-977a-cb8ac1d67a02.png)

**Comment by Enrico204** [comment]
Implemented, will be released into the next version :-)

**Comment by Termuellinator** [comment]
that was quick! Thanks for your efforts! :)
am i seeing it correct that just the minimize to tray on win10 is left for next release?

**Comment by Enrico204** [comment]
Apparently yes :-)

**Comment by avimar** [comment]
Hi -- does this distinguish between regular messages and muted messages?

I see the regular window shows there's messages in muted channels.

I imagine like slack -- a red circle for a direct message and another less bright circle (they chose pale-ish blue) for other messages, but that aren't urgent for you.

**Comment by Enrico204** [comment]
that sound interesting - to be honest, I use Telegram on daily basis and that behaviour is very useful, expecially with "noisy groups". I created #33 for this improvement :-)

**Comment by avimar** [comment]
I updated to master 43664a9477700e4ed06a61f3f5b728db8ae4fe34 to test the font-sizing on windows, but I realized that there haven't been any new tray icons when there should be an indicator. Any reason why..?

**Comment by Enrico204** [comment]
To be honest I didn't try it on Windows - maybe Windows doesn't like PNG as icon files. I'll do more testing :-)

**Comment by avimar** [comment]
There some way I can give you debug logs..?

**Comment by Enrico204** [comment]
You can run the app from Windows Command Prompt with `--debug-log` switch, it should print the debug log in command-line window :-)

**Comment by avimar** [comment]
Doesn't show much -- is there a way to get more debug info than `info`? The icon never changed.
On launch
```
<snip>
[06:29:25:0633] [info] Creating tray icon
[06:29:26:0059] [info] Badge updated:
[06:29:26:0731] [info] Badge updated:
<snip>
[06:29:30:0204] [info] Setting tray icon to warning
[06:29:30:0207] [info] Setting tray icon to normal
[06:29:30:0210] [info] Mask value: 1
[06:29:30:0456] [info] Badge updated: 1
[06:29:32:0206] [info] Setting tray icon to normal
[06:29:32:0212] [info] Mask value: 0
<read a muted channel -- the last of the unread messages>
[06:30:17:0602] [info] Badge updated:
```
Should the `Badge updated:` line show that something changed?

**Comment by Enrico204** [comment]
On "badge updated" message the app should change the icon (if the value is modified)

**Comment by avimar** [comment]
Ah. Well, the tray icon looks exactly the same.

**Comment by Enrico204** [comment]
I've checked - no change on Windows. I'll fix it soon :-)

**Comment by Enrico204** [comment]
Actually the fix was really easy... I forgot to add icon actions on Windows callback :-)
Now even on Windows the icon changes to indicate new messages

**Comment by avimar** [comment]
Works! Thanks so much!

I had to `rm -rf WhatsApp-win32-x64\` the dist, because `npm run build:win --overwrite` still gave me `Skipping win32 x64 (output dir already exists, use --overwrite to force)`

Now waiting on #33

**Comment by avimar** [comment]
... gosh, there's a lot of code for each platform. Is that purely due to slack have different title formatting, or the settings for tray icons?

... can you file upstream to get electron to deal with the cross-platform issues?

**Comment by Enrico204** [comment]
I'll do a complete check and refactoring soon :-)
