### ISSUE TITLE
Application closes instead of minimizing to tray [Windows 10]

### ISSUE THREAD

**Issue by 188Alex188** [Enrico204/Whatsapp-Desktop#23]
When I close the main window, tray icon disappears and application closes.

Please, add the function to close to tray.

**Comment by Enrico204** [comment]
Apparently that is a (Windows-only) bug - if you have the tray-icon enabled, it should be always close to tray icon.

**Comment by 188Alex188** [comment]
In my Linux systems (based on Debian) the tray icon works perfectly.

I take this opportunity to thank you for your great work.

**Comment by Enrico204** [comment]
Fixed :-)
