### ISSUE TITLE
voice notes sound like a robot

### ISSUE THREAD

**Issue by SuperSandro2000** [Enrico204/Whatsapp-Desktop#25]
Voice notes sound like a robot is talking on lowest volume level. Louder the issue is not present nor does whatsapp web has it or the app.

**Comment by Enrico204** [comment]
Uhm, there is no volume settings in Whatsapp-Desktop. What platform are you using? Can you please describe how can I reproduce that issue? Thanks :-)

**Comment by SuperSandro2000** [comment]
.... I misinterpreted the audio rate setting.... sry, for the inconvience

**Comment by Enrico204** [comment]
no problem :-)
