### ISSUE TITLE
Support for Elementary OS

### ISSUE THREAD

**Issue by giovannicaligaris** [Enrico204/Whatsapp-Desktop#26]
Is it possible to have support for Wingpanel? Right now the it has a colorfull icon but it would be ideal if it would be mono like the rest of the indicators.

Also, would it be possible to show notification (number) on Plank, similar to the official Whatsapp client for Mac?

![screenshot from 2017-08-27 20 27 35](https://user-images.githubusercontent.com/26255347/29753287-33353622-8b66-11e7-9d3c-11dd5bfa1abf.png)

![screen800x500](https://user-images.githubusercontent.com/26255347/29753291-4cb6a2c0-8b66-11e7-90ed-97ac53cae4dd.jpeg)

**Comment by Enrico204** [comment]
Apparently, [tray icons are no longer implemented in ElementaryOS 0.4](https://elementaryos.stackexchange.com/questions/4226/how-can-i-get-applications-to-display-a-system-tray-icon#4227). But I'll try to use the dock notification icon for that :-)

**Comment by giovannicaligaris** [comment]
They do, Ayatana was removed in the alpha version but they brought it back for the final stable release.

**Comment by Enrico204** [comment]
I've installed 0.4 Loki on my VM, there is no way to add the tray icon. Even if I'm using `electron 1.4.14` (which has the workaround for tray icons as described [here](https://github.com/electron/electron/issues/5050)), the icon doesn't show up.

Also, [HIG says that we should not have a notification icon (3rd point)](https://elementary.io/docs/human-interface-guidelines#system-indicators).

**Comment by giovannicaligaris** [comment]
Fine, I can live without the tray indicator but having the dock notification would be great.

Thank you

**Comment by Hativ3** [comment]
Many other apps have tray icons (or how they are named on Elementary OS), e.g. Telegram, KeePassXC, Seafile, ownCloud.

Look:
![trayicons](https://user-images.githubusercontent.com/12894547/30854971-9658acf2-a2b3-11e7-9416-99f1dfce640f.png)

**Comment by Enrico204** [comment]
I think that I'll find out how these apps are doing this - please note that I'm using Electron framework (over nodejs), so it might be more difficult than native code software (such as ownCloud, for instance).

**Comment by giovannicaligaris** [comment]
@Hativ3 Go to the Settings and select Show Tray icon

**Comment by Hativ3** [comment]
@giovannicaligaris I've checked it, but the icon doesn't show up.

**Comment by Enrico204** [comment]
@giovannicaligaris I've added calls to badge APIs for Electron, as far as I know that is the only thing that I can do using Electron. Can you please check if latest in `master` branch has the docker notification? Thanks :-)

**Comment by Hativ3** [comment]
For me it does not work. However I have Whatsapp from the DEB package installed, possibly there is a conflict. Let's see what @giovannicaligaris says. Tray icon is still not working for me.

**Comment by giovannicaligaris** [comment]
I can't build it. It keeps failing. I even tried just doing npm run build as well

$ npm run build:linux

> whatsapp-desktop@0.3.13 build:linux /home/caligaris/Downloads/Whatsapp-Desktop-master
> electron-packager ./app "WhatsApp" --out=dist --platform=linux --arch=x64 --electron-version=1.7.8 --icon=assets/win/whatsapp.ico

sh: 1: electron-packager: not found

npm ERR! Linux 4.10.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build:linux"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! whatsapp-desktop@0.3.13 build:linux: `electron-packager ./app "WhatsApp" --out=dist --platform=linux --arch=x64 --electron-version=1.7.8 --icon=assets/win/whatsapp.ico`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the whatsapp-desktop@0.3.13 build:linux script 'electron-packager ./app "WhatsApp" --out=dist --platform=linux --arch=x64 --electron-version=1.7.8 --icon=assets/win/whatsapp.ico'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the whatsapp-desktop package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./app "WhatsApp" --out=dist --platform=linux --arch=x64 --electron-version=1.7.8 --icon=assets/win/whatsapp.ico
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs whatsapp-desktop
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls whatsapp-desktop
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/caligaris/Downloads/Whatsapp-Desktop-master/npm-debug.log

**Comment by giovannicaligaris** [comment]
@Hativ3 the tray icon works for me, you have to enable it in Settings.

![screenshot from 2017-10-20 16 02 03](https://user-images.githubusercontent.com/26255347/31827570-0c73cd72-b5b0-11e7-8a60-a6c3a3ad2d38.png)

**Comment by Hativ3** [comment]
@giovannicaligaris I have, but it doesn't show up.

![bildschirmfoto von 2017-10-20 17-03-32](https://user-images.githubusercontent.com/12894547/31827773-b90aee50-b5b8-11e7-9e56-1b8cc0b7813c.png)

**Comment by giovannicaligaris** [comment]
@Hativ3 what is the version of the whatsapp installation?

**Comment by Hativ3** [comment]
@giovannicaligaris 0.3.13 via DEB package.

**Comment by giovannicaligaris** [comment]
@Hativ3 maybe try uninstalling it and removing the folder.

sudo apt purge --remove whatsapp-desktop
rm ~/.config/whatsapp-desktop

**Comment by Enrico204** [comment]
I was referring to dock notifications, not to the tray icon. Regarding the icon, maybe there is an incompatibility with some libraries - for instance, I still can't get tray icon showing in my elementaryOS VM

**Comment by giovannicaligaris** [comment]
@Enrico204 I was trying to test the dock but I wasn't able to compile the app.

**Comment by Enrico204** [comment]
Hi @giovannicaligaris , sorry I missed your previous post. I compiled latest `master` commit in a .tar.gz so you can test it :-)
Link: https://www.dropbox.com/s/vmkfkc4929tf8cp/WhatsApp-linux-x64.tar.gz?dl=0

**Comment by giovannicaligaris** [comment]
I don't see a notification (number) on the dock bar but a red indicator that there's a new message. Is that correct?

![screenshot from 2017-10-21 11 37 57](https://user-images.githubusercontent.com/26255347/31852516-dca90b72-b670-11e7-9810-36c566930256.png)

**Comment by Enrico204** [comment]
Yes. As far as I can tell, this is maximum that I can do using Electron APIs. Maybe in the future I can check if there is any way to call native code to do that.

**Comment by giovannicaligaris** [comment]
It's good enough for now. Good job.
