### ISSUE TITLE
Upgrading system

### ISSUE THREAD

**Issue by giovannicaligaris** [Enrico204/Whatsapp-Desktop#28]
Is it possible to have a PPA (ubuntu) or a notification on the app every time there's a new version?

**Comment by SuperSandro2000** [comment]
Follow here on github

**Comment by Enrico204** [comment]
I tried with launchpad (for PPA) but apparently the build platform cannot fetch esternal resources (ie. node and libraries outside official repos and other PPAs). Also they allow only sources (no binary uploads) so I can't upload the DEB package from Travis-CI. I think that I'll end up with a notification only.

**Comment by Daniel-McGuire** [comment]
Would a snap package not be better?

**Comment by giovannicaligaris** [comment]
Snap apps you can't be themed.

**Comment by Enrico204** [comment]
I added a basic update notification (and "About" window) in latest commit :-)
