### ISSUE TITLE
App window doesn't show up on top of other windows when restoring from tray icon

### ISSUE THREAD

**Issue by armnrd** [Enrico204/Whatsapp-Desktop#29]
# Environment Information
- Operating system: Fedora 26
- Desktop environment: Gnome 3
- WhatsApp Desktop version: 0.3.13
- Package source: Enrico204/Whatsapp-Desktop [RPM release](https://github.com/Enrico204/Whatsapp-Desktop/releases/download/v0.3.13/WhatsApp-0.3.13-1.x86_64.rpm)

# Problem
When I restore the app's window from the system tray icon, the window does show up on top of the other windows, and I have to manually set focus to it.

# Expected Behaviour
When restored from the tray icon, the window should show up on top of all other windows.

**Comment by Enrico204** [comment]
Hi @armnrd , I can't reproduce this problem on my Fedora installation (same as described). When I click on whatsapp desktop icon on left panel, the app shows on top of other windows, just as expected.

**Comment by armnrd** [comment]
Hi @Enrico204, I'm noticing some strange behaviour. Try these steps to reproduce the bug.

1. launch Whatsapp Desktop
2. close the window so that it minimizes to the tray
3. click on the tray icon, so that it is restored
(works fine so far)
4. change focus to windows from some other apps
5. close the Whatsapp Desktop window
6. click the tray icon to restore it
7. this time, it opens below the other windows

Are you able to reproduce the bug now? Perhaps it's to do with how my system is set up, but other applications, such as Skype (also uses Electron) and Telegram don't behave this way when restored from the tray.

This is the notification I see when what I see when I click the tray icon: ![notification screenshot](https://i.imgur.com/t3eGGKu.png)

**Comment by Enrico204** [comment]
Yes, now I'm seeing this strange behaviour :-)
I'll check and fix as soon as possible :-)

**Comment by Enrico204** [comment]
Fixed :-)

**Comment by armnrd** [comment]
Thanks! Now it functions as expected on my system. :-)
