### ISSUE TITLE
Linux Dependencies

### ISSUE THREAD

**Issue by cowonacid** [Enrico204/Whatsapp-Desktop#3]
Great Application :) :+1: 

First I failed to build on linux because of 2 missing packages. I fixed it by adding the 2 packages with:

`npm install --save node-gettext && npm install --save gettext-parser`

**Comment by Enrico204** [comment]
Hi @cowonacid , which distro are you using? Node version? Did you use "npm install" on both project root and "app/" subdir?
Thanks :-)
