### ISSUE TITLE
Wrong desktop notification title

### ISSUE THREAD

**Issue by armnrd** [Enrico204/Whatsapp-Desktop#30]
# Environment Information
- Operating system: Fedora 26
- Desktop environment: Gnome 3
- WhatsApp Desktop version: 0.3.13
- Package source: Enrico204/Whatsapp-Desktop [RPM release](https://github.com/Enrico204/Whatsapp-Desktop/releases/download/v0.3.13/WhatsApp-0.3.13-1.x86_64.rpm)

# Problem
The title for the native desktop notifications is wrong. [Screenshot](https://i.imgur.com/9uFhm9n.png)

# Expected Behaviour
The title should be WhatsApp Desktop instead of whatsapp-desktop.

**Comment by Enrico204** [comment]
Fixed in #31 by @veridiam :-)
