### ISSUE TITLE
text aliasing issue?

### ISSUE THREAD

**Issue by avimar** [Enrico204/Whatsapp-Desktop#32]
Somehow, the text is blurry on windows7.
I tried disabling "display scaling on high dpi" or "desktop composition" in the launch settings, but that didn't change anything.

The web version, in chromium, is much clearer text. Any clue?

![aliasing](https://user-images.githubusercontent.com/314077/30878772-3d9ba0e4-a306-11e7-9db3-b9c672b6ff88.png)

EDIT: You can't see it much from the screenshots...
EDIT2: I have windows set to Show text at Medium, 125% of the size, with clear type enabled.

**Comment by Enrico204** [comment]
Sorry I didn't have a Windows PC to test this, I'm installing Windows 10 on a spare PC that I recovered to find out why this behavior :-)

**Comment by Enrico204** [comment]
Hi @avimar , can you please check if this issue still in latest `master` commit? Thanks :-)

**Comment by avimar** [comment]
Just got back to my windows machine. Looks much better! Build from source was very straightforward.

Thanks!

**Comment by Enrico204** [comment]
Good to hear :-)
