### ISSUE TITLE
Menu bar hidden by default / option to hide

### ISSUE THREAD

**Issue by TechnoSparks** [Enrico204/Whatsapp-Desktop#35]
**This is a feature request**

The title is pretty self explanatory. I think it would add a little bit of eye candy if the menu bar is hidden by default, or maybe allow the user to hide the menu bar.

Of course, it should be accessible with the Alt button if required.

Thank you!

**Comment by Enrico204** [comment]
Yep, it would be useful. I'll do this after some bugfix :-)

**Comment by Enrico204** [comment]
Done :-)

**Comment by TechnoSparks** [comment]
awesome! Thank you so much!! :D I greatly appreciate it
