### ISSUE TITLE
Reload results in white screen

### ISSUE THREAD

**Issue by psmis2** [Enrico204/Whatsapp-Desktop#37]
Pressing reload will result in a white screen with only the title bar and the menubar showing.
Does not occur with the Windows version.

![whitescreen](https://user-images.githubusercontent.com/32421734/31154783-5c7933f0-a8a1-11e7-9fb6-4ee691b7354a.png)

Whatsapp-Desktop version:  v0.3.13

 OS: Fedora 
 Kernel: x86_64 Linux 4.12.14-300.fc26.x86_64
 Resolution: 3440x1440
 DE: KDE 5.36.0 / Plasma 5.10.5
 WM: KWin
 WM Theme: Breeze
 GTK Theme: Adwaita [GTK2], Default [GTK3]
 Icon Theme: breeze
 Font: Sans Serif
 CPU: Intel Core i7-5960X @ 16x 3.5GHz
 GPU: Gallium 0.4 on AMD FIJI (DRM 3.15.0 / 4.12.14-300.fc26.x86_64, LLVM 4.0.0)

**Comment by Enrico204** [comment]
Looks like that #36 and this issue are related to the same problem: a screen drawing issue. May be an incompatibility between your setup and Electron. I'll setup a VM with Fedora soon to check if my assumption is correct.

**Comment by Enrico204** [comment]
Hi @psmis2 , I cannot reproduce neither this issue or #38 in VM, so I'm still confident that this is a GPU driver issue. I made a command line switch `--disable-gpu` to force GPU disabling. Can you please try the latest code with that switch and see if that is a workaround? Thanks :-)

**Comment by psmis2** [comment]
Using the latest code and invoking it with the --disable-gpu indeed "solves" both this issue and #38 
It seems that the issue is caused by the opensource AMD graphics stack.

**Comment by Enrico204** [comment]
I've added an option to app's settings to make the CLI switch `--disable-gpu` persistent (so you can launch Whatsapp-Desktop from the launcher).
