### ISSUE TITLE
how to zoom/increase text size?

### ISSUE THREAD

**Issue by anthrotype** [Enrico204/Whatsapp-Desktop#39]

**Comment by Enrico204** [comment]
By now, the only way to increase font text is to use CSS (so if you don't know how to use CSS you will not be able to do what you're asking). By the way, I think that I may use this issue as an improvement to add this feature (into the settings) to a future version of the app.

**Comment by anthrotype** [comment]
Thanks. I'll use CSS for now.

**Comment by Enrico204** [comment]
I've implemented a switch in settings window :-)

**Comment by anthrotype** [comment]
Thanks a lot!

**Comment by msh2050** [comment]
please can you attach a sample css file 
I do not want to install from source (I think the rpm is not updated).
and the Css will give us more customization power

**Comment by Enrico204** [comment]
The CSS should be something like that:

    * {
       text-rendering: optimizeSpeed !important;
       -webkit-font-smoothing: subpixel-antialiased !important;
       font-size: large;
    }

**Comment by msh2050** [comment]
thanks for support.
