### ISSUE TITLE
Black system tray icon doesn't look cool on dark panel

### ISSUE THREAD

**Issue by ceyhunnabiyev** [Enrico204/Whatsapp-Desktop#4]
Whatsapp-Desktop version - 0.3.6 (AUR)

![screenshot from 2017-07-01 08-00-16](https://user-images.githubusercontent.com/5506156/27758966-5f917966-5e33-11e7-86ae-c59210e8da51.png)

It doesn't matter which system icons have chosen (Adwaita, Arc-Maia and etc.).

**Comment by Enrico204** [comment]
Fixed in 0.3.7 :-)

**Comment by ceyhunnabiyev** [comment]
Thanks a lot!! You are the best!!
