### ISSUE TITLE
Cannot add icon to Favorites on Ubuntu 17.10

### ISSUE THREAD

**Issue by orschiro** [Enrico204/Whatsapp-Desktop#41]
Another thing I noticed on Ubuntu 17.10.

All my applications have an option to add the icon to the favorites but just WhatsApp doesn't. 

Any ideas why?

![image](https://user-images.githubusercontent.com/170947/31327247-5a3b65be-acce-11e7-8645-0e7840da7e76.png)

![image](https://user-images.githubusercontent.com/170947/31327262-73614536-acce-11e7-801f-a6fe016b35af.png)

**Comment by Enrico204** [comment]
Hi @orschiro , I'll look for implementing this on next minor version :-)

**Comment by orschiro** [comment]
@Enrico204 awesome, thanks! :-)

**Comment by bil-elmoussaoui** [comment]
@Enrico204 It must be a missing StartupWMClass. The DE uses the StartupWMClass to match the running binary with the correct desktop file so it can be added to favorites or any other similiar action. 
You can use `xprop WM_CLASS` and then click on the application window to get the correct WM_CLASS.  
When you run it, you will get this output 
```
WM_CLASS(STRING) = "whatsapp-desktop", "whatsapp-desktop"
```
This line then should be added to the desktop file
`StartupWMClass=whatsapp-desktop`
Hope this helps

**Comment by Enrico204** [comment]
@orschiro Can you please test the latest version and check if this issue still present? Thanks :-)

**Comment by orschiro** [comment]
@Enrico204 yes, thank you. :-)

![image](https://user-images.githubusercontent.com/170947/34690244-ad2170f2-f4b8-11e7-87f8-88f40732bf3a.png)
