### ISSUE TITLE
Add an appdata file

### ISSUE THREAD

**Issue by baimafeima** [Enrico204/Whatsapp-Desktop#42]
For reference: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps

**Comment by bil-elmoussaoui** [comment]
@Enrico204 If you can provide this one, I can add the application to flathub (flatpak application repository) ;)

**Comment by Enrico204** [comment]
Yes, I'll write that file as soon as possible! :-)

**Comment by Enrico204** [comment]
@bil-elmoussaoui I've added the AppData also bundled in the flatpak, but I didn't tested it to check if it's correct (I merely followed the documentation). I can send you the flatpak binary if you can check it to see if it's correct :-)

**Comment by bil-elmoussaoui** [comment]
@Enrico204 You can add some information about the releases https://github.com/flathub/flathub/blob/112effb4bf7a482d9d0cc836c9bdf052245474de/com.obsproject.Studio.appdata.xml
The releases tag can also contain the changelog! You can also add other information like the developer name or the OARS https://hughsie.github.io/oars/
The more information/screenshot you get there. The better your application will look on any Linux software center

**Comment by bil-elmoussaoui** [comment]
Plus, when you run `appstream-util validate myappdatafile.xml` You get those two errors
```
appstream-util validate it.enrico204.whatsapp-desktop.appdata.xml      
it.enrico204.whatsapp-desktop.appdata.xml: FAILED:
? tag-missing           : <translation> not specified
? tag-missing           : <update_contact> is not present
Validation of files failed
```

**Comment by Enrico204** [comment]
strange, I ran the same utility but no error showed up. I added some tags, in time I'll expand them :-)
