### ISSUE TITLE
Closing main window requires restart ?

### ISSUE THREAD

**Issue by dhowe** [Enrico204/Whatsapp-Desktop#43]
I may be missing something obvious, but with the current build on OSX (10.10.5), if you close the main window, it appears impossible to re-open, though the app is still running. The only way to continue is to quit and restart the app...

**Comment by Enrico204** [comment]
Hi @dhowe , I'll try to check/debug ASAP, but I don't own an apple PC, so it might require some time. Thanks for you report! :-)

**Comment by dhowe** [comment]
Let me know if I can help

**Comment by Termuellinator** [comment]
i sometimes had a similar behaviour with whatsie - only way to get the window back was rmb on the tray icon and "open" - maybe this works in this case, too? ^^

**Comment by dhowe** [comment]
No 'open' button the the dock icon...

**Comment by dhowe** [comment]
I did find a workaround here (but it is not at all intuitive): select 'show' from the tiny whatsapp icon that is present in the menu

now if i just could figure out how to show unread message count on the dock icon, I would be all set

**Comment by Enrico204** [comment]
I've added a new option on the dock menu :-)

**Comment by dhowe** [comment]
This is great. But I think the standard behavior would be for a click on the dock icon to open the main window. This is, I believe, the standard behavior for OS X apps

**Comment by Enrico204** [comment]
ok let's see what I can do with Electron ;-)

**Comment by Enrico204** [comment]
Done :-)

**Comment by dhowe** [comment]
thanks much

**Comment by Enrico204** [comment]
Apparently this issue is back! :-(
