### ISSUE TITLE
Show unread message count on dock icon 

### ISSUE THREAD

**Issue by dhowe** [Enrico204/Whatsapp-Desktop#44]
Perhaps I am just missing the location for this option, but this seems a critically important feature. Otherwise one doesn't know when they have new messages...

Note: preferably this would only show the count for non-muted messages

**Comment by Enrico204** [comment]
Hi @dhowe , which OS do you use?

**Comment by dhowe** [comment]
OS X 10.10.5

**Comment by Enrico204** [comment]
Maybe #33 is related (at least for non-muted messages part)

**Comment by dhowe** [comment]
Interestingly this _used_ to work for me, until I switched over to the dev version.
Although the muted/non-muted functionality in #33 wasn't there, the basic message-count worked correctly in the dock on OS X

**Comment by Enrico204** [comment]
I'll check again the code that I modified in latest commits :-)
Thanks for feedback @dhowe :-)

**Comment by dhowe** [comment]
Any status on this? I'm finding it pretty unusable without this feature (as I never know when there is a message)

**Comment by Enrico204** [comment]
Sorry, I was quite busy in this period working on my degree thesis :-)
I'll have access to a macOS installation today in the afternoon, I'll check and fix this :-)

**Comment by Enrico204** [comment]
Bug found and fixed :-)
