### ISSUE TITLE
Clickcable notofication request

### ISSUE THREAD

**Issue by MarconiGRF** [Enrico204/Whatsapp-Desktop#45]
I actually don't know if notifications are clickable or not in current version, but at the moment isn't working yet here. And if you could add that function, that will be awesome! Just like the clickable notification available in chrome but instead of that, a system clickable notification.

WhatsApp-Desktop version: 0.3.13-1_amd64
System distro/version: Debian GNU Linux 9.2, Gnome Desktop Manager 3.

**Comment by Enrico204** [comment]
Actually notifications are handled by Gnome (in that setup), and triggered by Whatsapp code itself. It should be the same as Chrome, AFAIK. Unfortunately there is no way around this, I think. If anyone have any ideas on how interact with Whatsapp side to take over notification handling, I'll be happy to reopen this issue and code about this :-)
