### ISSUE TITLE
Mute all notifications

### ISSUE THREAD

**Issue by cubedtear** [Enrico204/Whatsapp-Desktop#46]
Telegram desktop has a "Disable notifications" option in the context menu on the tray icon, as well as a checkbox in the options menu,

It would be great to have the same option with whatsapp desktop, in order to mute all notifications (no sound, and no notification, not just being able to lower their volume), if possible from tray icon.

**Comment by Enrico204** [comment]
I think that this can be easily done :-)

**Comment by Enrico204** [comment]
Implemented :-)

**Comment by cubedtear** [comment]
Building... Thank you!
