### ISSUE TITLE
Window won't get focus if notification is clicked

### ISSUE THREAD

**Issue by flexo3001** [Enrico204/Whatsapp-Desktop#51]
On GNOME (tested on 3.24 and 3.26) the chat window won't get focused if it's clicked. Is it possible to add this since it's a common functionality?
Tested on Fedora 26 and 27.

**Comment by Enrico204** [comment]
Sorry, notifications are handled by the system itself - I have no control on that. I can look for workarounds or something like that, so I'll keep this issue open for a while and I'll update for any news ;-)

**Comment by flexo3001** [comment]
Hm, for reference this [electron client](https://github.com/saenzramiro/rambox) can do this. Unfortunately i know Electron or JS for writing an PR, but i can help with testing.

**Comment by Enrico204** [comment]
Thanks for the hint - I'll check if I can do the same :-)

**Comment by Enrico204** [comment]
Implemented :-)
Will be released in 0.4.1 :-)
