### ISSUE TITLE
Ubuntu 14.04 32bit can't install from source

### ISSUE THREAD

**Issue by ouboub** [Enrico204/Whatsapp-Desktop#52]
Hi

I tried to compile and followed all the step indicated in the readme file.
in the final step I obtained
npm run build:linux

> whatsapp-desktop@0.3.14 build:linux /home/oub/src/Whatsapp-Desktop-0.3.14
> electron-packager ./app "WhatsApp" --out=dist --platform=linux --arch=x64 --electron-version=1.7.8 --icon=assets/win/whatsapp.ico

/usr/bin/env: node: No such file or directory
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

any suggestions?

Uwe Brauer

**Comment by Enrico204** [comment]
Actually there was no support for 32-bit hosts. I've added a build command for 32-bit Linux platform in the last commit :-)
(the command that you're using is for x64 builds)

**Comment by Enrico204** [comment]
For instance, the new command is `npm run build:linux32` :-)
