### ISSUE TITLE
ubuntu 14.04 32, after last commit and pull error message

### ISSUE THREAD

**Issue by ouboub** [Enrico204/Whatsapp-Desktop#53]
HI

I pulled some seconds again in order to try out the last commit for 32bit.
After running 
npm install   
I obtained 
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/oub/ALLES/src/Whatsapp-Desktop/npm-debug.log
npm ERR! not ok code 0

I attach the log file
[npm-debug.log](https://github.com/Enrico204/Whatsapp-Desktop/files/1485824/npm-debug.log)

**Comment by Enrico204** [comment]
Please don't open a new issue if you still have the same problem. You should comment under the previous issue.
Anyway, I saw (in npm-debug.log) that you're using a very old nodejs/npm version. Please upgrade to latest stable release.
