### ISSUE TITLE
Client does not remember window size

### ISSUE THREAD

**Issue by christianfl** [Enrico204/Whatsapp-Desktop#55]
Hey! Thanks for this standalone client.

If you change the size of the window and close the client it does not remember the old size after starting it again. It also does not remember whether it was used in fullscreen or "window"-mode. Everytime it starts as a small windows again.
Maybe this can be fixed? For example the Signal desktop client (also electron based) does remember the window size correctly.

Thanks in advance,
Christian

**Comment by Enrico204** [comment]
Yes, of course it can be fixed :-)
I'll resolve this ASAP :-)

**Comment by ajyotirmay** [comment]
I find this behavior a bit awkward too, but luckily that's an easy fix :D

**Comment by Enrico204** [comment]
fixed, will be released soon :-)
