### ISSUE TITLE
[BUG] No Icon displayed on KDE Menu

### ISSUE THREAD

**Issue by Lord-Haji** [Enrico204/Whatsapp-Desktop#57]
Although its showing up right on the notifications tray, but no icon shows up in the KDE Menu

**Comment by Enrico204** [comment]
Which distro are you using? Version of KDE?

**Comment by Enrico204** [comment]
Hi @Lord-Haji , I'm closing this issue because I can't reproduce this behavior. If you still have this issue on latest release, feel free to reopen this issue :-)
