### ISSUE TITLE
[Ubuntu 16.04][startup application] automatically deleted from startup application

### ISSUE THREAD

**Issue by pgallir** [Enrico204/Whatsapp-Desktop#58]
After reboot, startup application list miss the (newly created) item for  /path\to\Whatsapp-Desktop/dist/WhatsApp-linux-x64/WhatsApp. I wonder whether this behavior is due to "Whatsapp-Desktop" or my OS, but it actually does not happen for other programs.

**Comment by Enrico204** [comment]
I'll download Ubuntu and test this app soon to investigate :-)

**Comment by Enrico204** [comment]
Hi @pgallir , can you please confirm that this issue is present on latest version? Thanks :-)

**Comment by pgallir** [comment]
let me test a bit longer. that behavior seems ok now. ;)

**Comment by Enrico204** [comment]
Thanks! Please wait for the 0.4.2 release, because 0.4.1 is causing major issues right now :-)

**Comment by Enrico204** [comment]
Hi @pgallir , I'm closing this issue. If the problem still, feel free to reopen it :-)
