### ISSUE TITLE
Tray icon click doesn't fire

### ISSUE THREAD

**Issue by Enrico204** [Enrico204/Whatsapp-Desktop#6]
Click on tray icon (on Linux platform) doesn't show up main window.

**Comment by Enrico204** [comment]
Fixed in version 0.3.8

**Comment by KottV** [comment]
Hi.
What DE do you use? Under KDE5 click on tray icon always opens menu (hide|show/quit) only, so I have to select show/hide.
I guess, this is due AppIndicator implementation in KDE.

**Comment by Enrico204** [comment]
Yes, I forgot to mention Fluxbox. Unfortunately this is platform-depedent (in this case, also DE-dependent).

**Comment by KottV** [comment]
I see. Thnx.
