### ISSUE TITLE
Setting to turn off auto-emoji

### ISSUE THREAD

**Issue by peterthomassen** [Enrico204/Whatsapp-Desktop#62]
Thanks a lot for the great work! :+1: 

Whenever I type :-) and such, it is replaced by an emoji, and I have to hit backspace to get back to the ASCII representation. For me, this sort of autocorrect is very inconvenient.

To insert an emoji, I can still use the emoji tool next to the text field.

Therefore, I would like to propose adding a setting to turn off automatic text-to-emoji conversion?

**Comment by Enrico204** [comment]
Uhm, I don't know if it's possible, as emoji are managed by the official code itself (remember: this "app" is only a wrapper around official WhatsApp web). I'll look at the code and then I'll update this issue :-)

**Comment by Enrico204** [comment]
I tried to look inside the app code, but there is no way AFAIK to disable this behavior, sorry :-(
