### ISSUE TITLE
Global keyboard shortcut to show the app

### ISSUE THREAD

**Issue by rbbernardino** [Enrico204/Whatsapp-Desktop#63]
First, thank you very much for the great app! 

I would like to know if there is any chance for you to add the possibility of defining a global shortcut to show the app. I'm using Linux Mint.

Right now I'm just defining a new shortcut to call the "WhatsApp" command, which detects there is already an instance running and show it. But I think a way to do it from the app would be better. What do you think?

Thank you for your attention!

**Comment by Enrico204** [comment]
I think that it's possible, but it might be requires a lot of time. I'll look at this when all bugs are solved :-)

**Comment by manjuransari143** [comment]
@rbbernardino You can create a custom shortcut to launch the WhatsApp application. The steps are:
1. Navigate to Setting -> Keyboard -> Shorcuts -> Custom Shortcuts
2. Click on add custom shorcut.
3. Write the name of shortcut, and in command write the location of the whatsapp application (in my case it is /opt/whatsapp-desktop/WhatsApp)
4. Save it. And voila!, your work is done.

**Comment by Enrico204** [comment]
Resolved by @manjuransari143 with #93 :-)
