### ISSUE TITLE
Runtime error due to OS X dock code

### ISSUE THREAD

**Issue by bpartridge** [Enrico204/Whatsapp-Desktop#65]
I'm getting the following error when running `npm run dev` on Mac OS 10.11.6:

<img width="372" alt="screenshot 2017-12-04 13 09 37" src="https://user-images.githubusercontent.com/20748/33568498-9c95e356-d8f4-11e7-8f08-402ea1238df5.png">

Looks like this commit is what introduced that: https://github.com/Enrico204/Whatsapp-Desktop/commit/e5a6af95e4debdfcd099ff732a34461a325947ec

There's no mention in https://electronjs.org/docs/all#appdockbouncetype-macos of any method `app.dock.on` - was this meant to be `app.on('activate', ...)`?

I'm happy to make a PR if so.

**Comment by Enrico204** [comment]
That's strange, because I though that these lines were needed (on my machine) for dock activation (eg. click on dock icon). Of course you can make a PR :-)
Can you please verify if the behavior of dock icon is what is expected? (eg. opening the main window on click)
Thanks :-)

**Comment by Enrico204** [comment]
Is this problem still in version 0.4 ?

**Comment by Enrico204** [comment]
I've tested it in macOS High Sierra, this issue still in.
