### ISSUE TITLE
After closing the Whatsapp  window on a Mac, it's impossible to open the window again

### ISSUE THREAD

**Issue by Defrilitus** [Enrico204/Whatsapp-Desktop#66]
After closing the Whatsapp-Desktop window on a Mac, it's impossible to open the window again from Whatsapp's dock icon. It's necessary to quit the program and restart it every time.

**Comment by Enrico204** [comment]
Hi @Defrilitus , actually this issue was resolved in #43 and scheduled to be released into the next version (also see #65 , maybe it will delay the release) :-)

**Comment by Defrilitus** [comment]
Sorry, I missed #43. Thanks for your work; looking forward to the new release!

**Comment by Enrico204** [comment]
No problem :-)
