### ISSUE TITLE
Minimize to tray on startup not working

### ISSUE THREAD

**Issue by ttjimera** [Enrico204/Whatsapp-Desktop#69]
I am running Linux Mint 18.3 on Cinnamon 3.6.6. I ticked the "Minimize to tray on startup" in the setting. But Whatsapp-Desktop still start maximized each time.

**Comment by Defrilitus** [comment]
This is true also on macOS 10.13.2. I suspect that all app settings are Windows-only.
Incidentally, the "approved" way to start an app minimized on macOS is to include it in System Preferences/Users & Groups/Login Items with the "Hide" checkbox checked.
However, though this does cause Whatsapp-Desktop to start on login, the program won't start minimized (the official Whatsapp app has the same problem, among others).
I have resolved this by launching Whatsapp-Desktop with an Applescript that not only hides the program on startup, but also resolves issue #55.
The script is pretty basic, but I'm adding it here in case it can be useful for anyone:
_--start Whatsapp-Desktop
tell application "WhatsApp" to activate
--resize window (resolve issue #55)
tell application "System Events"
	tell application "System Events" to tell application process "WhatsApp"
		try
			get properties of window 1
                        --set window size/position to your preference
			set size of window 1 to {1020, 350}
			set position of window 1 to {770, 380}
		end try
	end tell
end tell
--hide WhatsApp (resolve issue #69)
tell application "System Events"
	set visible of application process "WhatsApp" to false
end tell_
In addition, to avoid issue #43 on a Mac, use Better Touch Tool to set the Whatsapp-Desktop "close" button to "hide". Works beautifully.

**Comment by msnjuegos** [comment]
Same problem in Debian Stretch. Any solution for linux?

**Comment by Enrico204** [comment]
Uhm, have you tried with latest code from repository? This issue seems identical to #47 (which is resolved in latest code, not yet released)

**Comment by Defrilitus** [comment]
Could Enrico let us know which Whatsapp-Desktop settings are Windows-only and which are (at least in theory) platform-independent? I haven't been able to make any of them work on macOS. Am I missing something? Thanks in advance!

**Comment by Enrico204** [comment]
@Defrilitus all features listed in README are platform-independent, unless specified (currently, none). If something is not working on macOS, you can open an issue (before doing that please check if there is a closed issue already on that).

**Comment by Defrilitus** [comment]
Will do, but will first wait for version 0.4. Thanks.

**Comment by Enrico204** [comment]
@ttjimera Please check if this bug still in latest release. If it does, feel free to reopen this issue and I'll investigate :-)

**Comment by ttjimera** [comment]
@Enrico204 yes it is now starting up minimized. Thanks for the support.

**Comment by Enrico204** [comment]
You're welcome! :-)
