### ISSUE TITLE
Remove platform-dependent switches on Settings window when using an incompatible platform

### ISSUE THREAD

**Issue by Enrico204** [Enrico204/Whatsapp-Desktop#71]
### System details

* App Version: github

### Expected behavior

The Settings window should hide/disable all switches that have no effect on current environment

### Actual behavior

The Settings window shows all switches regardless of the platform.

**Comment by Defrilitus** [comment]
Or, at least as a temporary measure, mark the various settings according to platform dependency. I would be pleased to help with Windows and Mac, but have never used Linux.

**Comment by Enrico204** [comment]
I think that I can extract those infos from Electron documentation. Then I'll check on GNU/Linux, and I'll be pleased if you can help me testing on macOS and Windows :-)

**Comment by Defrilitus** [comment]
Sure, no problem. I'd be happy to help.

**Comment by Enrico204** [comment]
I'm working on some of these things, and I found mentions about tray icon for macOS on Electron documentation. Maybe it's not named "tray icon area", but there are some icons near the clock placed by apps. I think that Electron is referring to these. May I ask you to check if "Show Tray Icon" have any effect on macOS?

**Comment by Defrilitus** [comment]
The documentation that you mention is referring to what is known in macOS as the [menu bar](https://support.apple.com/kb/PH25077?locale=en_GB) or, to be more precise, the status menus in the menu bar.
At present, "Show Tray Icon" has no effect on macOS. "Minimize to tray", on the other hand, while also having no effect on the menu bar, causes issue #43 right at app start-up. I had to delete settings.json to get Whatsapp-Desktop working again.
Hope this helps.

**Comment by Enrico204** [comment]
Ok, so the safer option is to disable incompatibile options :-)

**Comment by Defrilitus** [comment]
Definitely ;-)
Below is the current status (version 0.3.14) of the various options in macOS:

Hide Avatars
Doesn’t work — disable on macOS

Hide Message Previews
Works — enable on macOS

Show Tray Icon
Doesn’t work — disable on macOS

Minimize to tray on start-up
Works—but do not enable on macOS until #43 has been definitely resolved (otherwise it's impossible to open the WhatsApp-Desktop window).

Autostart on login
Doesn’t work — disable on macOS 

Autohide menu bar
Doesn’t work — disable on macOS

Disable GPU
Not sure; how do I check whether it’s working or not?

**Comment by Enrico204** [comment]
Uhm,

* Hide Avatars: this should be marked as a bug, not as "platform-dependent feature". I'll check it again on Linux ASAP, as it should depend only on the rendering engine (not on any platform API)
* Minimize to tray on start-up: I think that #43 is resolved in latest repo code - soon I'll release 0.4, so we can make this test again :-)
* Autostart on login: as before, this should be marked as a bug (at least because the option that I'm using claims to be compatible with macOS)
* Disable GPU: actually, I don't know how to check this. On buggy hardware was very easy :-P
I think that I'll skip this for now (or mark it as Linux-only, as I'm sure that this options works on Linux platform).

I'll work on these very soon :-)
Thanks :-)

**Comment by Defrilitus** [comment]
Actually, the autostart on login does work—to an extent on macOS—but incorrectly. Whatsapp-Desktop is started under Terminal, which is basically debug mode, and gives plenty of error messages. I can send them to you, but I don't think that it's worth your time to investigate further at the moment; especially as anyone who uses macOS probably knows that the way for users to autostart programs at login is to add them to "System Preferences/Users & Groups/Login Items" (the equivalent of the "Startup" folder in Windows). In any case, I'll wait until the next version release to file any more bugs… You have enough on your plate at the moment :-)

**Comment by Enrico204** [comment]
Ok I've disabled autostart, tray icon and autohide menu on macOS, and fixed a bug with the "Hide Avatars" option which was not working properly. I'm releasing 0.4, so I think that we may close this issue :-)
You can open a new issue for any bug that you'll find on app version 0.4 (yes, I'm sure there will be many of them) :-)
