### ISSUE TITLE
Segmentation fault on application

### ISSUE THREAD

**Issue by teras** [Enrico204/Whatsapp-Desktop#73]
### System details

* OS: Linux
* App Version: 0.3.14-1_amd64
* If Linux, Desktop Environment: Ubuntu 17.10

### Expected behavior

Not to crash

### Actual behavior

Crashes

### Step to reproduce the behavior

$  /opt/whatsapp-desktop/WhatsApp --debug-log
Segmentation fault (core dumped)

$ gdb /opt/whatsapp-desktop/WhatsApp            
...
Reading symbols from /opt/whatsapp-desktop/WhatsApp...(no debugging symbols found)...done.
(gdb) start
Temporary breakpoint 1 at 0x3e3c9b0
Starting program: /opt/whatsapp-desktop/WhatsApp 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
(gdb) continue
Continuing.
[New Thread 0x7fffe880d700 (LWP 27127)]

Thread 1 "WhatsApp" received signal SIGSEGV, Segmentation fault.
0x0000000001efb3b3 in ?? ()

I am sorry I don't know what more information to append

## EDIT
I tried the current github version, again sigfaults

**Comment by Enrico204** [comment]
I suspect that this is an upstream bug - I'll check in a few days (sorry I'm out of town in these days) :-)

**Comment by teras** [comment]
I don't know why... today It works.
The only thing I can imagine was to reboot my computer...
