### ISSUE TITLE
How do I change entire look of the app on Linux?

### ISSUE THREAD

**Issue by nexus38** [Enrico204/Whatsapp-Desktop#75]
### System details

* App Version:  whatsapp-desktop_0.3.14-1_amd64.deb
* If Linux, Desktop Environment: **Ubuntu 17.04 Unity** with kernel: **4.14.6-041406-generic**

I just want to change theme of the app like a chrome extension **Stylish** https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew

I changed some .css files from the source and build it for linux but nothing happened. Please guide me:)

**Comment by Enrico204** [comment]
You don't need to modify CSS files provided in the app, you can add your own CSS (in the Settings window) :-)
