### ISSUE TITLE
Using latest installed font

### ISSUE THREAD

**Issue by bbbf0621** [Enrico204/Whatsapp-Desktop#76]
Linux Mint 18.3 Cinnamon 3.6.7

I'm expecting fonts to change according to system fonts

### Actual behavior

Whatsapp Desktop uses latest installed font and i cannot change it unless i uninstall fonts it is using.

**Comment by Enrico204** [comment]
As this is a web-app, it's normal behavior to use fonts specified in the web page style. However, you can always change the font by applying a custom CSS.
