### ISSUE TITLE
On macOS "start minimized" and "close window" are unusable

### ISSUE THREAD

**Issue by Defrilitus** [Enrico204/Whatsapp-Desktop#77]
Happy New Year and thank you for version 0.4! There are a lot of improvements (especially remembering the last window size), but—unfortunately—there remain problems with the "minimize to tray on start-up" option as well as pressing the "close window" button on macOS.

Let me divert to an explanation of macOS's window buttons. Like Windows, macOS has three and they generally correspond to those of Windows: maximize (green), minimize (orange) and close window (red). The big difference between Windows and macOS is the latter: when one closes the last window of a program in Windows, the program closes; in macOS, the fact that the last window closes doesn't mean that the program itself exits. A program in macOS can still be running without any windows; especially a program like Whatsapp-Desktop which basically sits there waiting for messages (for example, closing the window on iMessages or Apple Mail doesn't prevent them from remaining alive and, for exampe, labeling the dock when new messages are received).

When "minimize to tray on start-up" is checked, Whatsapp-desktop doesn't start with the window minimized: it starts without a window. That would be fine, but when clicking on the dock icon, nothing happens (this is issue #43 all over again). The same is true when pressing the red (close window button). The only option is to quit the app and start all over again. In the case of "minimize to tray on start-up), the only way to resolve the situation is to quit the app and change "startminimized" in settings.json to "no".

I realize that you don't have macOS on your computer, so maybe a help would be a Teamviewer (or similar) meeting to show you the problem first hand. In any case, thanks for all your work!

**Comment by Enrico204** [comment]
Actually, I thought that #43 was resolved, but it's not. Unfortunately I don't have a stable access to a macOS, so I cannot test the app every time :-(
I'll try to fix this, maybe I can send you binaries to test if I can't access an apple pc :-)

**Comment by Enrico204** [comment]
Hi @Defrilitus , can you please test this version for me?
https://www.dropbox.com/s/o7h5izpncg0dv4j/WhatsApp-darwin-x64.zip?dl=0

(this is the latest code from repo, the issue that you describe should be fixed in this version - I was able to run a macOS VM)

**Comment by Defrilitus** [comment]
Bingo! All issues mentioned above have been completely resolved. Thank you.
Just curious as to why this version is just 127.5 MB, compared to 367.7 MB of the version released yesterday.

**Comment by Enrico204** [comment]
Dunno, maybe a native build is better (this one was made on macOS, standard releases are made on GNU/Linux) :-)

**Comment by Defrilitus** [comment]
Definitely better! You can release this immediately, if you want. Thanks again.
