### ISSUE TITLE
Whatsapp-Desktop 0.4.1 not working for me on macOS

### ISSUE THREAD

**Issue by Defrilitus** [Enrico204/Whatsapp-Desktop#80]
I installed 0.4.1, but it won't start on macOS (please see attached screenshot). Not sure what's wrong, as the beta version that you made available for me on 1 Jan works perfectly (I've reinstalled it); but the latest update is worse than useless on a Mac.
Another comment—not urgent—but you really should compile macOS versions on macOS as those compiled elsewhere are about three times the size. I'm perfectly willing to help.
![whatsapp-desktop 0 4 1 error](https://user-images.githubusercontent.com/34283333/34506865-79a0bb0c-effe-11e7-8672-7cd7f875d273.png)

**Comment by Enrico204** [comment]
Yesterday I had some issues on Travis-CI which I'm using to build released binaries. I'll investigate and fix it asap!

**Comment by Defrilitus** [comment]
Version 0.4.2 is AOK on macOS. Thank you.
