### ISSUE TITLE
the new version of the app, 0.4.1-1, is not working on my system

### ISSUE THREAD

**Issue by ipasi68** [Enrico204/Whatsapp-Desktop#81]
### System details

* OS: Linux mint 18.3, cinnamon, english
* App Version: whatsapp-desktop_0.4.1-1_amd64.deb
* If Linux, Desktop Environment: cinnamon

### Expected behavior

Launch and run the application succesfully

### Actual behavior

The application won't start

### Step to reproduce the behavior

pretty simple, tried to launch the app from the menu and it's not working... I'll reinstall the old version

**Comment by chrisvdb** [comment]
Same here:

`$ /opt/whatsapp-desktop/WhatsApp
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'node-gettext'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/opt/whatsapp-desktop/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /opt/whatsapp-desktop/resources/app/main.js:11:23
    at Object.<anonymous> (/opt/whatsapp-desktop/resources/app/main.js:810:3)
    at Object.<anonymous> (/opt/whatsapp-desktop/resources/app/main.js:812:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)`

**Comment by giovannicaligaris** [comment]
I am having the same issue on .deb and .flatpak

**Comment by OmarMorando** [comment]
Same problem with .deb and tar.gz

**Comment by hayco** [comment]
me too on:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```

**Comment by Enrico204** [comment]
Yesterday I had some issues on Travis-CI which I'm using to build released binaries. I'll investigate and fix it asap!

**Comment by tkerst** [comment]
Same problem here, workaround was to run 
`# npm install node-gettext`
`# npm install`
in /opt/Whatsapp/resources/app. 
The first command installs the missing module while the second one installs the dependencies that are defined in the package.json. Those were missing too in my case (Arch Linux via aur/whatsapp-desktop).

**Comment by llorllale** [comment]
@tkerst thanks for the workaround!

**Comment by Enrico204** [comment]
Yes, I have some issues with packaging with Travis-CI. I'll fix asap
