### ISSUE TITLE
Build macOS releases on macOS

### ISSUE THREAD

**Issue by Enrico204** [Enrico204/Whatsapp-Desktop#83]
On Travis-CI, use macOS environment when building macOS app releases.

**Comment by Defrilitus** [comment]
Thanks :-)

**Comment by Enrico204** [comment]
I just tried to build macOS version on macOS (with Travis-CI), and it seems to be the same size (~130MB). I need to investigate futher :-(

**Comment by defrilitus** [comment]
That's certainly not the size of the current macOS app, which is now 367 MB (which has remained pretty steady). Are you looking at the zip size or the app size? The only time that the app size was around 130 MB was when you compiled it on a Mac. In any case, thanks for continuing to look into this. If I can help in any way, just let me know.

**Comment by Enrico204** [comment]
I was referring to the ZIP size, which is somehow related to the real size. I've just found an hint about the presence of symlinks inside the app folder, so I modified the c-i in order to preserve symlinks into ZIPs. I'm testing it :-)

**Comment by defrilitus** [comment]
If you look at the beta release that you linked me to on 1 Jan, the zip size was 50 MB and the unzipped app size was 127 MB. As far as I know, this was the only macOS version that you have compiled on a Mac—you told me so ;-)

**Comment by Enrico204** [comment]
Yes, but I tried with Travis-CI (the continuous integration service that I use) which has macOS build service, and the size is the same as Linux version.

I think that the difference is the symlink flag enabled by default on macOS when you ZIP folder using Finder.

Can you please check if the size is "normal" on the ZIP for 0.4.2 (current version)? I just recompiled it, zipped with `-y` flag (preserve symlinks) and replaced it.

**Comment by defrilitus** [comment]
Bingo! 50.8 MB zip size and 127.5 MB app size. You've hit the nail on the head :-) Thanks. You're extremely good at solving app problems quickly and successfully! Much appreciated.

**Comment by Enrico204** [comment]
Well actually I'm very good to use google :-P
I'm happy to see that was so easy to fix :-)
I modified the build script and now I'm testing it on Travis, it should be ok :-)
Thanks for testing!

**Comment by defrilitus** [comment]
As I said, much appreciated ;-)
