### ISSUE TITLE
[Feature request] Image preview when try send photos in file manager.

### ISSUE THREAD

**Issue by usernatilds** [Enrico204/Whatsapp-Desktop#84]
### System details
* OS: Debian Buster, en-us
* App Version: 0.4.2
* If Linux, Desktop Environment: LXDE

### Expected behavior
Image preview in file manager before send photos
See example:
![8](https://user-images.githubusercontent.com/25496130/34532964-4f1c6ae2-f09f-11e7-8ab0-9a9639a36bf3.png)

### Actual behavior

Not appear image preview when try send image, in whatsapweb using chrome appear
![49](https://user-images.githubusercontent.com/25496130/34533021-81d2dc78-f09f-11e7-87fd-aba7952f4f41.png)

### Step to reproduce the behavior
When try send a photo for a friend.

**Comment by Enrico204** [comment]
Unfortunately, Electron doesn't support this in current version AFAIK. I'll keep updating Electron, in the meantime there is nothing that I can do :-(
