### ISSUE TITLE
Update Option in App Itself

### ISSUE THREAD

**Issue by mzeeqazi** [Enrico204/Whatsapp-Desktop#86]
### System details

* OS: Linux Mint 18.3
* App Version: 0.3.14
* If Linux, Desktop Environment: Cinnamon 

It is always good to have update app option available in app itself or ateast there should be resources to update app from apt-get(or apt) itself. The version available at software manager( app store) is still 0.3.14

**Comment by Enrico204** [comment]
I tried to upload whatsapp-desktop to Launchpad PPA but unfortunately it's not compatible. I wrote to packagecloud.io staff to know if there is any way to have more space/bandwidth than the "free" account, as Electron is very huge. I'll update this accordingly :-)

**Comment by Enrico204** [comment]
`packagecloud.io` granted us some space to host packages, now we have a repository! :-)
Details in `readme.md` (or in github project page).
