### ISSUE TITLE
App starts minimized but tray icon has (only) hide option

### ISSUE THREAD

**Issue by chrisvdb** [Enrico204/Whatsapp-Desktop#87]
### System details

* OS: Kubuntu 17.10
* App Version: 0.4.2-1

### Expected behavior

App starts minimized, right click on tray icon show 'show' and 'quit'.

### Actual behavior

App starts minimized, right click on tray icon show 'hide' and 'quit'.

### Step to reproduce the behavior

Start app with 'Minimize to tray on startup' setting on.

**Comment by Enrico204** [comment]
Fixed :-)
