### ISSUE TITLE
Flaptak package requires freedesktop runtime 1.4 when the last available is 1.6

### ISSUE THREAD

**Issue by diazbastian** [Enrico204/Whatsapp-Desktop#88]
### System details

* OS: [GNU/Linux 64-bit]
* App Version: [v0.4.2]
* If Linux, Desktop Environment: [Fedora 27 - XFCE]

### Expected behavior

When installing the flatpak bundle, use the available dependencies (freedesktop runtime 1.6)

### Actual behavior

When installing, request a not available dependency (the process is not completed).

### Step to reproduce the behavior

• Go to the release page
• Select the Flatpak bundle package to download
• Once downloaded, install (Eg using the terminal with the default options: `flatpak install it.enrico204.whatapp-desktop_master_x64.flatpak`).

Note: Thank you for providing this application in this format. If in the near future it is available on flathub.org, I don't doubt that it will become the unofficial WhatsApp application of reference in GNU/Linux.

**Comment by Enrico204** [comment]
Same as #79, we'll track it there :-)
