### ISSUE TITLE
add the version number as a suffix to the archives files

### ISSUE THREAD

**Issue by bil-elmoussaoui** [Enrico204/Whatsapp-Desktop#92]
Can you please add the version number as a suffix to the .tar.gz  files? 

This causes a small issue: The package manager downloads the .tar.gz file and keep it in a cache folder. If you download the next version, the file won't be downloaded as it's the same file name. So it will compare the two sha256 and it will result in a not passed validity check error! 

Adding the version number suffix to those files should fix it ;)

**Comment by Enrico204** [comment]
Yes it's definitively needed! Thanks :-)
I'll modify travis-ci config for the next release :-)

**Comment by Enrico204** [comment]
Done :-)
