### ISSUE TITLE
monochrome icon

### ISSUE THREAD

**Issue by kupiqu** [Enrico204/Whatsapp-Desktop#95]
current green icon in the systray is too salient, could it be possible to display a monochrome icon, instead?

![image](https://user-images.githubusercontent.com/3875196/34860457-8c9f07f2-f72b-11e7-86cd-958b639826da.png)

**Comment by bil-elmoussaoui** [comment]
Sadly, Electron doesn't support (yet) using an icon from the current theme used by the user.  If you want to override this icon, and make it look the way you want, you can replace it manually in /opt/whatsapp-desktop/resources` or just use https://github.com/bil-elmoussaoui/Hardcode-Tray which will do the job for you ;)

**Comment by Enrico204** [comment]
`Hardcode-Tray` is the way :-)
Unfortunately Electron doesn't support many things :-(

**Comment by kupiqu** [comment]
I'll try it out. Thank you.
