### ISSUE TITLE
No Icon tray KDE 5.11.5

### ISSUE THREAD

**Issue by ssergio-ll** [Enrico204/Whatsapp-Desktop#96]
### System details

* OS: KDE NEON 5.11
* App Version: 0.4.2
* Desktop Environment: KDE 5.11.5

### Expected behavior

Show icon of whatapp on tray.

### Actual behavior

I select the option "Minimize to icon tray" but this not show icon. 

### Step to reproduce the behavior

Install App and select option "Minimize to icon tray".

**Comment by Enrico204** [comment]
It might be similar to #40, I'll investigate further asap :-)

**Comment by ssergio-ll** [comment]
Similar but this happen on KDE

**Comment by Enrico204** [comment]
Apparently it's the same issue. As workaround, you can remove `libappindicator-gtk2`. See this comment: https://github.com/itchio/itch/issues/1106#issuecomment-355411831
Unfortunately, we need to wait for the upstream project Electron to fix this :-(

**Comment by Enrico204** [comment]
Let's track both at #40
