### ISSUE TITLE
Spell check does not work on Kubuntu

### ISSUE THREAD

**Issue by chrisvdb** [Enrico204/Whatsapp-Desktop#97]
### System details

* OS: Kubuntu 17.10
* App Version: 0.4.2

### Expected behavior

Spell check works.

### Actual behavior

Spell check is not active.

### Step to reproduce the behavior

Launch Whatsapp-Desktop on Kubuntu (not tested in other environments).

**Comment by nackenho** [comment]
Spell check also doesn't work on  
**System details**       

- Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.3 Sylvia
- App Version: 0.4.2

**Comment by rbbernardino** [comment]
For me too, same setup as @nackenho and it just doesn't work.

**System details**
- Desktop: Cinnamon 3.6.7 (Gtk 3.18.9-1ubuntu3.3) dm: mdm Distro: Linux Mint 18.3 Sylvia
- App Version: 0.4.2

**Comment by Enrico204** [comment]
Confirmed: apparently the embedded Chromium library dropped the support for spellcheck. I need to pick an external library and embed it.

**Comment by Enrico204** [comment]
As the issue is the same for all OSes, let's track it on #16
